kind: ConfigMap
apiVersion: v1
metadata:
  name: collections
data:
  collections.json: |-
    [
      {"name":"none","display_name":"None"},
      {"name":"demo_collection","display_name":"Red Hat Docs"},
      {"name":"pdf_collection","display_name":"PDF"}
      {"name":"LangChainCollection","display_name":"LangChainCollection"}
    ]