---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-app
  labels:
    component: vllm
    purpose: vllm-app
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: vllm/gpu/gitops
    repoURL: >-
      https://github.com/arckrish/simple-llm-rag-demo
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true